# Generated by Django 5.1.1 on 2024-09-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_member_ids_server_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='avatar',
            field=models.CharField(default='/assets/images/server_avatars/default.jpg', max_length=255),
        ),
    ]
