# Generated by Django 5.1.1 on 2024-09-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
