# Generated by Django 5.1.1 on 2024-09-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_delete_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='type',
            field=models.CharField(default=10, max_length=256),
            preserve_default=False,
        ),
    ]
