# Generated by Django 5.1.1 on 2024-09-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_server_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='type',
            field=models.CharField(default='Direct', max_length=256),
        ),
    ]
