# Generated by Django 5.1.1 on 2024-09-29 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_server_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_message', to='chat.server'),
        ),
    ]
