# Generated by Django 5.1.1 on 2024-10-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_message_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='qr_code',
            field=models.CharField(default='/assets/images/server_avatars/default.jpg', max_length=255),
        ),
    ]
