# Generated by Django 5.1.1 on 2024-10-19 10:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_server_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='blocked',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
