# Generated by Django 5.1.1 on 2024-11-01 08:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_server_staffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='banned',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
