# Generated by Django 4.2.15 on 2024-09-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='/assets/images/avatars/default.jpg', max_length=255),
        ),
    ]
