# Generated by Django 4.2.15 on 2024-09-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_notification_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='timestamp',
        ),
    ]
