# Generated by Django 5.1.1 on 2024-09-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_user_current_elo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_elo',
        ),
    ]
