# Generated by Django 5.1.1 on 2024-11-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0014_user_otp_secret_user_two_factor_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_banner',
            field=models.CharField(default='/assets/images/banners/default_banner.png', max_length=255),
        ),
    ]
