# Generated by Django 5.1.1 on 2024-11-19 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0015_user_profile_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.ManyToManyField(blank=True, related_name='user_blocked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
