# Generated by Django 5.1.1 on 2024-09-23 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.CharField(default='/assets/images/tournament_avatars/default.jpg', max_length=255)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('game_name', models.CharField(choices=[('pong', 'Pong'), ('space_invaders', 'Space Invaders'), ('road_fighter', 'Road Fighter')], max_length=20)),
                ('total_number_of_players', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('game_name', models.CharField(choices=[('pong', 'Pong'), ('space_invaders', 'Space Invaders'), ('road_fighter', 'Road Fighter')], max_length=20)),
                ('total_games_played', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Tournament Stats',
            },
        ),
        migrations.CreateModel(
            name='Tournament_Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('game_id', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament_history')),
            ],
        ),
    ]
