# Generated by Django 5.1.1 on 2024-11-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament_history',
            name='last_game',
            field=models.IntegerField(default=0),
        ),
    ]
