# Generated by Django 5.1.1 on 2024-09-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament_bracket',
            options={'verbose_name_plural': 'Tournament Brackets'},
        ),
        migrations.AlterModelOptions(
            name='tournament_history',
            options={'verbose_name_plural': 'Tournament History'},
        ),
        migrations.RemoveField(
            model_name='tournament_bracket',
            name='round_number',
        ),
        migrations.AddField(
            model_name='tournament_bracket',
            name='round_name',
            field=models.CharField(choices=[('round_of_16', 'Round of 16'), ('quarterfinals', 'Quarterfinals'), ('semifinals', 'Semifinals'), ('finals', 'Finals')], default='round_of_16', max_length=20),
        ),
    ]
