# Generated by Django 5.1.1 on 2024-11-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_history_last_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament_history',
            name='last_game',
        ),
        migrations.AlterField(
            model_name='tournament_history',
            name='status',
            field=models.CharField(choices=[('Waiting for players', 'Waiting for players'), ('Ended', 'Ended'), ('In progress', 'In progress')], default='Waiting for players', max_length=25),
        ),
    ]
