# Generated by Django 5.1.1 on 2024-11-11 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_history_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament_Bracket',
        ),
    ]
