# Generated by Django 5.1.1 on 2024-11-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournamentroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=255)),
                ('user_id1', models.IntegerField(default=0)),
                ('user_id2', models.IntegerField(default=0)),
                ('score_user1', models.IntegerField(default=0)),
                ('score_user2', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tournamentroom',
            options={'verbose_name_plural': 'Tournament Rooms'},
        ),
        migrations.AddField(
            model_name='tournamentroom',
            name='qr_code',
            field=models.CharField(default='/assets/images/tournament_qr_code/default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='tournamentroom',
            name='room_size',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='tournament_history',
            name='avatar',
            field=models.CharField(default='/assets/images/tournament_avatars/default_tournament.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournamentroom',
            name='avatar',
            field=models.CharField(default='/assets/images/tournament_avatars/default_tournament.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='tournamentroom',
            name='matchs',
            field=models.ManyToManyField(blank=True, to='tournaments.matchtournament'),
        ),
    ]
