# Generated by Django 5.1.1 on 2024-11-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournamentroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentroom',
            options={'verbose_name_plural': 'Tournament Rooms'},
        ),
    ]
