# Generated by Django 5.1.1 on 2024-11-10 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_matchtournament_alter_tournamentroom_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentroom',
            name='matchs',
        ),
        migrations.AddField(
            model_name='tournamentroom',
            name='matchs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.matchtournament'),
        ),
    ]
