# Generated by Django 5.1.1 on 2024-11-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_tournamentroom_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentroom',
            name='qr_code',
            field=models.CharField(default='/assets/images/tournament_qr_code/default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='tournamentroom',
            name='room_size',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='tournament_history',
            name='avatar',
            field=models.CharField(default='/assets/images/tournament_avatars/default_tournament.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournamentroom',
            name='avatar',
            field=models.CharField(default='/assets/images/tournament_avatars/default_tournament.jpg', max_length=255),
        ),
    ]
