# Generated by Django 5.1.1 on 2024-11-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournamentroom_room_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentroom',
            name='avatar',
            field=models.CharField(default='/assets/images/tournament_avatars/default_tournament.jpg', max_length=255),
        ),
    ]
