# Generated by Django 5.1.1 on 2024-11-10 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_remove_tournamentroom_matchs_tournamentroom_matchs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentroom',
            name='matchs',
        ),
        migrations.AddField(
            model_name='matchtournament',
            name='tournament_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentroom'),
        ),
    ]
