# Generated by Django 5.1.1 on 2024-11-10 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_remove_tournamentroom_matchs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtournament',
            name='tournament_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournamentroom'),
        ),
    ]
