# Generated by Django 5.1.1 on 2024-11-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_tournamentroom_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament_history',
            name='avatar',
            field=models.CharField(default='/assets/images/tournament_avatars/default_tournament.jpg', max_length=255),
        ),
    ]
