# Generated by Django 5.1.1 on 2024-11-11 09:02

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_matchtournament_tournament_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament_bracket',
            name='score_user1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament_bracket',
            name='score_user2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament_bracket',
            name='user_id1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament_bracket',
            name='user_id2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament_history',
            name='members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='tournament_history',
            name='qr_code',
            field=models.CharField(default='/assets/images/tournament_qr_code/default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='tournament_history',
            name='room_size',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='tournament_bracket',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament_history'),
        ),
        migrations.DeleteModel(
            name='MatchTournament',
        ),
        migrations.DeleteModel(
            name='TournamentRoom',
        ),
    ]
