# Generated by Django 5.1.1 on 2024-11-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_tournament_bracket_score_user1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament_bracket',
            name='game_id',
            field=models.IntegerField(default=0),
        ),
    ]
