# Generated by Django 5.1.1 on 2024-11-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_alter_tournament_bracket_game_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament_history',
            name='members',
        ),
        migrations.AddField(
            model_name='tournament_history',
            name='bracket_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='tournament_history',
            name='qr_code',
            field=models.CharField(default='/assets/images/servers_qr_codes/default.jpg', max_length=255),
        ),
        migrations.DeleteModel(
            name='Tournament_Bracket',
        ),
    ]
