# Generated by Django 5.1.1 on 2024-11-12 10:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_remove_tournament_history_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament_history',
            name='members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
