global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '${EMAIL_HOST_USER}'
  smtp_auth_username: '${EMAIL_HOST_USER}'
  smtp_auth_password: '${EMAIL_HOST_PASSWORD}'
  smtp_require_tls: true

route:
  receiver: 'email-alerts'
  group_by: ['severity', 'job', 'instance']

receivers:
  - name: 'email-alerts'
    email_configs:
      - to: '${EMAIL_HOST_USER}'
        send_resolved: true