global:
  scrape_interval: 15s 
  evaluation_interval: 15s


alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - "alertmanager-container:9093"


rule_files:
  - "/etc/prometheus/rules.yml"

scrape_configs:
  - job_name: "user_management_service"
    metrics_path: "/metrics"
    static_configs:
      - targets: 
        - "user-management-container:8000"
  
  - job_name: "chat_service"
    metrics_path: "/metrics"
    static_configs:
      - targets: 
        - "chat-container:8001"
  
  - job_name: "game_service"
    metrics_path: "/metrics"
    static_configs:
      - targets: 
        - "game-container:8002"
  
  - job_name: "tournaments_service"
    metrics_path: "/metrics"
    static_configs:
      - targets: 
        - "tournaments-container:8003"

  - job_name: "cadvisor"
    static_configs:
      - targets:
        - "cadvisor-container:8080"
  
  - job_name: 'redis'
    static_configs:
      - targets:
        - 'redis-exporter-container:9121'

  - job_name: "postgres"
    static_configs:
      - targets:
        - "postgres-exporter:9187"

