# Generated by Django 5.1.1 on 2024-10-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_server_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='qr_code',
            field=models.CharField(default='/assets/images/servers_qr_codes/default_qr_code.png', max_length=255),
        ),
    ]
