# Generated by Django 5.1.1 on 2024-10-29 07:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_message_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='staffs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
