# Generated by Django 5.1.1 on 2024-11-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_server_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='qr_code',
            field=models.CharField(default='/assets/images/servers_qr_codes/default.jpg', max_length=255),
        ),
    ]
