# Generated by Django 5.1.1 on 2024-09-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_game_match_game_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestats',
            old_name='game_type',
            new_name='game_name',
        ),
        migrations.AddField(
            model_name='game_history',
            name='game_name',
            field=models.CharField(choices=[('pong', 'Pong'), ('space_invaders', 'Space Invaders'), ('road_fighter', 'Road Fighter')], default='pong', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game_history',
            name='game_type',
            field=models.CharField(choices=[('ranked', 'Ranked'), ('local', 'Local'), ('ai', 'AI')], max_length=20),
        ),
    ]
