# Generated by Django 5.1.1 on 2024-10-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_game_type_gamestats_game_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_history',
            name='winner',
            field=models.IntegerField(default=0),
        ),
    ]
