# Generated by Django 5.1.1 on 2024-11-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_gamestats_istournemantmatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestats',
            name='isTournemantMatch',
        ),
        migrations.AddField(
            model_name='game_history',
            name='isTournemantMatch',
            field=models.BooleanField(default=False),
        ),
    ]
