# Generated by Django 5.1.1 on 2024-11-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_gamestats_istournemantmatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_history',
            name='tournamet_id',
            field=models.IntegerField(default=0),
        ),
    ]
