# Generated by Django 5.1.1 on 2024-11-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_game_history_tournamet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_history',
            old_name='tournamet_id',
            new_name='tournament_id',
        ),
    ]
