# Generated by Django 5.1.1 on 2024-11-14 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_rename_tournamet_id_game_history_tournament_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestats',
            name='peak_elo',
        ),
    ]
