# Generated by Django 5.1.1 on 2024-11-20 20:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_remove_gamestats_peak_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestats',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
