# Generated by Django 5.1.1 on 2024-11-20 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_rename_made_at_gamestats_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestats',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
