# Generated by Django 4.2.15 on 2024-09-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('game_invitation', 'Game Invitation'), ('friend_request', 'Friend Request'), ('strike', 'Strike')], max_length=255),
        ),
    ]
