# Generated by Django 5.1.1 on 2024-09-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_alter_user_is_playing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_elo',
            field=models.IntegerField(default=25),
        ),
    ]
